# Generated by Django 4.2.11 on 2025-07-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://imgs.search.brave.com/k0aUkD_2r1uX9P78hJIIiSsZJsfr4B0qQpxkaphHfAM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/cHJlbWl1bS12ZWN0/b3IvbWVudS1yZXN0/YXVyYW50XzI0OTA4/LTI0MTExLmpwZz9z/ZW10PWFpc19oeWJy/aWQmdz03NDA', max_length=500),
        ),
    ]
